Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: accounts/user_update.html
"GET /accounts/profile/ HTTP/1.1" 500 80809
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /accounts/update_profile
"GET /accounts/update_profile HTTP/1.1" 404 5078
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/update_profile HTTP/1.1" 301 0
Internal Server Error: /accounts/update_profile/
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: accounts/user_update.html
"GET /accounts/update_profile/ HTTP/1.1" 500 81009
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/update_profile/ HTTP/1.1" 200 741
Internal Server Error: /accounts/update_profile/
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 206, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py", line 81, in form_valid
    response = super().form_valid(form)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 119, in get_success_url
    if self.success_url:
       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/utils/functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
"POST /accounts/update_profile/ HTTP/1.1" 500 116109
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/update_profile/
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 206, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/views.py", line 86, in form_valid
    response = super().form_valid(form)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/views/generic/edit.py", line 119, in get_success_url
    if self.success_url:
       ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/utils/functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
"POST /accounts/update_profile/ HTTP/1.1" 500 116109
/Users/santiagovasquezfranco/Desktop/order_system/apps/accounts/urls.py changed, reloading.
Watching for file changes with StatReloader
"POST /accounts/update_profile/ HTTP/1.1" 302 0
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /accounts/profile/ HTTP/1.1" 500 124112
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_profile' not found. 'edit_profile' is not a valid view function or pattern name.
"GET /accounts/profile/ HTTP/1.1" 500 126150
"GET /accounts/profile/ HTTP/1.1" 200 692
"GET /accounts/update_profile/ HTTP/1.1" 200 737
"POST /accounts/update_profile/ HTTP/1.1" 302 0
"GET /accounts/profile/ HTTP/1.1" 200 696
/Users/santiagovasquezfranco/Desktop/order_system/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/manage.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/manage.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/register HTTP/1.1" 301 0
"GET /accounts/register/ HTTP/1.1" 200 9504
"GET /static/assets/img/curved-images/curved6.jpg HTTP/1.1" 404 1922
"POST /accounts/register/ HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 200 9000
"GET /static/assets/img/curved-images/curved6.jpg HTTP/1.1" 404 1922
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2309
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2360
/Users/santiagovasquezfranco/Desktop/order_system/apps/producto/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/santiagovasquezfranco/Desktop/order_system/apps/inventario/models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2309
"GET //admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 9491
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/css/base.css HTTP/1.1" 200 22120
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /admin/inventario/insumos/ HTTP/1.1" 200 10237
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
"GET /static/admin/js/actions.js HTTP/1.1" 200 8076
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/inventario/insumos/add/ HTTP/1.1" 200 12908
"GET /static/admin/css/forms.css HTTP/1.1" 200 8525
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
"GET /admin/inventario/movimientoinsumo/ HTTP/1.1" 200 10305
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/add/ HTTP/1.1" 200 17123
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /admin/authtoken/tokenproxy/ HTTP/1.1" 200 10624
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /admin/accounts/user/ HTTP/1.1" 200 18308
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /admin/authtoken/tokenproxy/ HTTP/1.1" 200 10624
"GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 12644
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/authtoken/tokenproxy/add/ HTTP/1.1" 302 0
"GET /admin/authtoken/tokenproxy/ HTTP/1.1" 200 11891
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 9909
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2360
"GET /admin/inventario/insumos/ HTTP/1.1" 200 10237
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /admin/inventario/insumos/add/ HTTP/1.1" 200 12908
"GET /static/admin/css/forms.css HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0
"GET /admin/inventario/movimientoinsumo/ HTTP/1.1" 200 10305
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/add/ HTTP/1.1" 200 17123
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
"GET /static/admin/js/calendar.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
"GET /admin/inventario/insumos/ HTTP/1.1" 200 10237
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/add/ HTTP/1.1" 200 12908
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/inventario/insumos/add/ HTTP/1.1" 302 0
"GET /admin/inventario/insumos/ HTTP/1.1" 200 11786
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /admin/inventario/insumos/1/change/ HTTP/1.1" 200 13215
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/ HTTP/1.1" 200 10305
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/add/ HTTP/1.1" 200 17181
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/inventario/movimientoinsumo/add/ HTTP/1.1" 302 0
"GET /admin/inventario/movimientoinsumo/1/change/ HTTP/1.1" 200 17848
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/ HTTP/1.1" 200 11561
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/1/change/ HTTP/1.1" 200 13215
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/ HTTP/1.1" 200 11712
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/add/ HTTP/1.1" 200 17181
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/inventario/movimientoinsumo/add/ HTTP/1.1" 302 0
"GET /admin/inventario/movimientoinsumo/ HTTP/1.1" 200 12358
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/1/change/ HTTP/1.1" 200 17551
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/ HTTP/1.1" 200 11561
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/ HTTP/1.1" 200 11561
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/1/change/ HTTP/1.1" 200 13215
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/inventario/insumos/1/change/ HTTP/1.1" 302 0
"GET /admin/inventario/insumos/ HTTP/1.1" 200 11809
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/movimientoinsumo/ HTTP/1.1" 200 12116
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/inventario/insumos/ HTTP/1.1" 200 11575
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
